modLoader = "javafml"
loaderVersion = "[${forge_major_version},)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "no_nv_flash"
version = "${file.jarVersion}"
displayName = "No Night Vision Flashing"
updateJSONURL = "https://raw.github.com/cofh/version/main/no_nv_flash/update.json"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming, covers1624"
description = '''
No more night vision flashing!
'''
[[dependencies.no_nv_flash]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "AFTER"
side = "BOTH"

[[dependencies.no_nv_flash]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "AFTER"
side = "BOTH"
